# Generated by Django 3.2.18 on 2023-05-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_volonturees_type_of_animals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donation',
        ),
    ]
