# Generated by Django 3.2.18 on 2023-05-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20230503_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='type_of_animal',
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pets.shelter'),
            preserve_default=False,
        ),
    ]
    
