# Generated by Django 3.2.18 on 2023-05-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20230504_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnmore',
            old_name='info',
            new_name='text',
        ),
    ]
