# Generated by Django 3.2.18 on 2023-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_rename_info_learnmore_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
